name: Build 

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
    
    - name: Release
      run: cargo build --release
    - uses: actions/upload-artifact@v3
      with:
        name: client-linux
        path: target/release/client-backend
        retention-days: 7
      
      
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Release
      run: cargo build --release
    - uses: actions/upload-artifact@v3
      with:
        name: client-windows
        path: target/release/client-backend.exe
        retention-days: 7
